[package]
name = "RustyEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-watch = "8.5.3"
wgpu = "27.0.1"
winit = "0.30.12"
thiserror = "2.0.17"
log = "0.4"
env_logger = "0.11.8"
pollster = "0.4.0"
